import { AssessmentQuestion } from '@/types';

export const BLOCK_LABELS: Record<string, { title: string; description: string }> = {
  your_work: { title: 'About Your Work', description: "Let's understand what you do every day." },
  ai_experience: { title: 'Your AI Experience', description: 'Where are you now with AI tools?' },
  your_goals: { title: 'Your Goals', description: 'Last few questions — almost done!' },
};

export const ASSESSMENT_QUESTIONS: AssessmentQuestion[] = [
  // Block 1: Your Work (4 questions)
  {
    id: 'q1_work_area',
    block: 'your_work',
    question: 'Which best describes your work area?',
    type: 'single',
    options: [
      { value: 'admin_ops', label: 'Administration / Office Operations' },
      { value: 'finance', label: 'Finance / Accounting' },
      { value: 'hr', label: 'HR / People Operations' },
      { value: 'marketing', label: 'Marketing / Communications' },
      { value: 'sales', label: 'Sales' },
      { value: 'it_support', label: 'IT / Tech Support' },
      { value: 'project_mgmt', label: 'Project Management' },
      { value: 'customer_service', label: 'Customer Service' },
      { value: 'legal', label: 'Legal' },
      { value: 'management', label: 'Management / Leadership' },
      { value: 'other', label: 'Other' },
    ],
  },
  {
    id: 'q2_daily_tasks',
    block: 'your_work',
    question: 'What do you spend the most time on in a typical work week? (Select your top 3)',
    type: 'multi',
    options: [
      { value: 'writing', label: 'Writing documents / reports' },
      { value: 'data', label: 'Analyzing data / spreadsheets' },
      { value: 'clients', label: 'Communicating with clients' },
      { value: 'managing', label: 'Managing people / teams' },
      { value: 'presentations', label: 'Creating presentations' },
      { value: 'processing', label: 'Processing / organizing information' },
      { value: 'research', label: 'Research' },
      { value: 'scheduling', label: 'Scheduling / coordination' },
      { value: 'creative', label: 'Creative work / design' },
      { value: 'troubleshooting', label: 'Problem-solving / troubleshooting' },
      { value: 'physical', label: 'Manual / physical tasks' },
      { value: 'calls', label: 'Phone / video calls' },
    ],
  },
  {
    id: 'q3_computer_pct',
    block: 'your_work',
    question: 'What percentage of your workday is spent in front of a computer?',
    type: 'slider',
    slider_min: 0,
    slider_max: 100,
    slider_labels: ['0%', '100%'],
  },
  {
    id: 'q4_repetitive',
    block: 'your_work',
    question: 'How much of your daily work follows a predictable, repeatable pattern?',
    type: 'single',
    options: [
      { value: '1', label: 'Every day is completely different' },
      { value: '2', label: 'Mostly different with some routine' },
      { value: '3', label: 'About half routine, half new' },
      { value: '4', label: 'Mostly routine with some variety' },
      { value: '5', label: 'I do essentially the same things every day' },
    ],
  },

  // Block 2: AI Experience (5 questions)
  {
    id: 'q8_tools_used',
    block: 'ai_experience',
    question: 'Which of these have you personally used for work tasks?',
    type: 'multi',
    options: [
      { value: 'chatgpt', label: 'ChatGPT' },
      { value: 'claude', label: 'Claude' },
      { value: 'copilot', label: 'Copilot / Bing AI' },
      { value: 'gemini', label: 'Google Gemini' },
      { value: 'image_ai', label: 'Midjourney / DALL-E' },
      { value: 'embedded', label: 'AI features in software I already use (e.g., Grammarly, Excel Copilot)' },
      { value: 'other', label: 'Other AI tools' },
      { value: 'none', label: 'None of these' },
    ],
  },
  {
    id: 'q9_ai_usage',
    block: 'ai_experience',
    question: 'When you last used an AI tool for work, what did you do?',
    type: 'multi',
    options: [
      { value: 'question', label: 'Asked it a simple question' },
      { value: 'write', label: 'Had it write or edit text' },
      { value: 'analyze', label: 'Used it to analyze data' },
      { value: 'brainstorm', label: 'Used it to brainstorm ideas' },
      { value: 'summarize', label: 'Used it to summarize something' },
      { value: 'code', label: 'Used it to code or create formulas' },
      { value: 'none', label: "I haven't used AI for work" },
    ],
  },
  {
    id: 'q10_ai_output',
    block: 'ai_experience',
    question: 'When AI gives you a response, what do you typically do?',
    type: 'single',
    options: [
      { value: 'as_is', label: 'Use it as-is' },
      { value: 'minor_edits', label: 'Make minor edits' },
      { value: 'major_rewrite', label: 'Substantially rewrite it' },
      { value: 'starting_point', label: 'Use it as a starting point and rebuild' },
      { value: 'revise', label: 'Ask AI to revise it' },
      { value: 'depends', label: 'It depends on the task' },
    ],
  },
  {
    id: 'q11_confidence',
    block: 'ai_experience',
    question: 'If asked to use AI to turn a messy dataset into an executive summary with recommendations, how confident would you feel?',
    type: 'single',
    options: [
      { value: '1', label: "I wouldn't know where to start" },
      { value: '2', label: "I'd struggle but could try" },
      { value: '3', label: 'I could probably figure it out' },
      { value: '4', label: "I'd be fairly comfortable" },
      { value: '5', label: 'I could do this easily right now' },
    ],
  },
  {
    id: 'q12_error_detection',
    block: 'ai_experience',
    question: 'Have you ever gotten a result from AI that was clearly wrong or misleading?',
    type: 'single',
    options: [
      { value: 'caught_fast', label: 'Yes — I caught it immediately' },
      { value: 'caught_slow', label: 'Yes — but it took me a while to notice' },
      { value: 'unsure', label: "I'm not sure" },
      { value: 'no', label: 'No' },
      { value: 'not_enough', label: "I haven't used AI enough to say" },
    ],
  },

  // Block 3: Your Goals (4 questions)
  {
    id: 'q_new_tools',
    block: 'your_goals',
    question: 'How do you typically react when a new tool or process is introduced at work?',
    type: 'single',
    options: [
      { value: 'jump_in', label: 'I jump in and figure it out' },
      { value: 'show_me', label: "I'll try it if someone shows me first" },
      { value: 'wait', label: 'I wait until I have to use it' },
      { value: 'stick', label: 'I prefer sticking with what works' },
    ],
  },
  {
    id: 'q25_time_available',
    block: 'your_goals',
    question: 'How much time per week could you realistically dedicate to learning new skills?',
    type: 'single',
    options: [
      { value: '<1', label: 'Less than 1 hour' },
      { value: '1-2', label: '1-2 hours' },
      { value: '3-5', label: '3-5 hours' },
      { value: '5+', label: '5+ hours' },
      { value: 'none', label: 'I genuinely have no spare time' },
    ],
  },
  {
    id: 'q26_reason',
    block: 'your_goals',
    question: "What's the main reason you're taking this assessment?",
    type: 'single',
    options: [
      { value: 'worried', label: "I'm worried about my job security" },
      { value: 'ahead', label: 'I want to get ahead of the curve' },
      { value: 'company', label: 'My company suggested it' },
      { value: 'curious', label: "I'm just curious" },
      { value: 'learn', label: "I want to use AI better but don't know where to start" },
    ],
  },
  {
    id: 'q28_value',
    block: 'your_goals',
    question: 'What would be most valuable to you right now?',
    type: 'single',
    options: [
      { value: 'clear_picture', label: 'A clear picture of how AI affects my specific role' },
      { value: 'hands_on', label: 'Hands-on practice using AI for my actual work tasks' },
      { value: 'plan', label: 'A step-by-step plan to make myself more valuable' },
      { value: 'proof', label: "Proof I can show my employer that I'm AI-ready" },
      { value: 'peace', label: 'Honestly, just peace of mind' },
    ],
  },
];
