import { TestProfile } from './types.js';

function answers(map: Record<string, string | string[] | number>) {
  return Object.entries(map).map(([question_id, value]) => ({ question_id, value }));
}

export const PROFILES: Record<string, TestProfile> = {
  junior_marketing: {
    name: 'QA_JuniorMarketing',
    email: 'qa-junior-mkt@awf-test.local',
    description: 'Junior marketer, surface-level AI user, low confidence',
    roleProfile: {
      job_description: 'Junior marketing coordinator at a 50-person tech startup. I write social media posts, draft newsletters, and create campaign briefs.',
      pain_point_task: 'Writing monthly performance reports from Google Analytics data — takes me hours to summarize the numbers into readable insights.',
      typical_morning: 'Check email, review social media comments, draft 2-3 posts, attend standup, work on current campaign brief.',
      tools_used: ['Google Workspace', 'Canva', 'Mailchimp', 'ChatGPT occasionally'],
      industry: 'technology',
      company_size: '50-100',
    },
    assessment: answers({
      q1_work_area: 'marketing',
      q2_daily_tasks: ['writing', 'creative', 'clients'],
      q3_computer_pct: 90,
      q4_repetitive: '3',
      q8_tools_used: ['chatgpt'],
      q9_ai_usage: ['write'],
      q10_ai_output: 'major_rewrite',
      q11_confidence: '2',
      q12_error_detection: 'unsure',
      q_new_tools: 'show_me',
      q25_time_available: '1-2',
      q26_reason: 'worried',
      q28_value: 'hands_on',
    }),
  },

  senior_finance: {
    name: 'QA_SeniorFinance',
    email: 'qa-senior-fin@awf-test.local',
    description: 'Senior finance professional, AI skeptic, no AI experience',
    roleProfile: {
      job_description: 'Senior financial analyst at a multinational manufacturing company. I prepare quarterly reports, manage budgets across 3 departments, and do variance analysis.',
      pain_point_task: 'Monthly budget reconciliation across 3 cost centers — manually comparing SAP exports with departmental spreadsheets for discrepancies.',
      typical_morning: 'Review overnight emails from Asia team, check P&L dashboards, process expense approvals, prepare for finance review meeting.',
      tools_used: ['SAP', 'Excel', 'PowerBI', 'Outlook'],
      industry: 'manufacturing',
      company_size: '500+',
    },
    assessment: answers({
      q1_work_area: 'finance',
      q2_daily_tasks: ['data', 'processing', 'writing'],
      q3_computer_pct: 95,
      q4_repetitive: '4',
      q8_tools_used: ['none'],
      q9_ai_usage: ['none'],
      q10_ai_output: 'as_is',
      q11_confidence: '1',
      q12_error_detection: 'not_enough',
      q_new_tools: 'wait',
      q25_time_available: '<1',
      q26_reason: 'company',
      q28_value: 'clear_picture',
    }),
  },

  mid_hr: {
    name: 'QA_MidHR',
    email: 'qa-mid-hr@awf-test.local',
    description: 'Mid-level HR, moderate AI user, overwhelmed collector',
    roleProfile: {
      job_description: 'HR Business Partner at a 200-person logistics company. I handle recruitment for 2 departments, employee relations, and quarterly engagement surveys.',
      pain_point_task: 'Writing personalized rejection emails for the 30+ candidates we interview each month — they all need different tones and specific feedback.',
      typical_morning: 'Screen CVs from overnight applications, respond to employee queries on Teams, prepare for 2-3 interviews, update recruitment tracker.',
      tools_used: ['BambooHR', 'LinkedIn Recruiter', 'Microsoft 365', 'ChatGPT', 'Gemini'],
      industry: 'logistics',
      company_size: '200-500',
    },
    assessment: answers({
      q1_work_area: 'hr',
      q2_daily_tasks: ['managing', 'writing', 'scheduling'],
      q3_computer_pct: 80,
      q4_repetitive: '4',
      q8_tools_used: ['chatgpt', 'gemini'],
      q9_ai_usage: ['write', 'summarize'],
      q10_ai_output: 'minor_edits',
      q11_confidence: '3',
      q12_error_detection: 'caught_slow',
      q_new_tools: 'show_me',
      q25_time_available: '1-2',
      q26_reason: 'curious',
      q28_value: 'plan',
    }),
  },

  junior_admin: {
    name: 'QA_JuniorAdmin',
    email: 'qa-junior-admin@awf-test.local',
    description: 'Junior admin assistant, no AI, resistant to change',
    roleProfile: {
      job_description: 'Administrative assistant at a law firm with 15 attorneys. I manage calendars, file documents, answer phones, and handle incoming mail.',
      pain_point_task: 'Filing and organizing case documents — scanning, naming, categorizing, and uploading 50+ documents per week into the document management system.',
      typical_morning: 'Sort incoming mail, check attorney calendars for conflicts, answer phones, file yesterday\'s documents, prepare conference rooms.',
      tools_used: ['Microsoft Office', 'iManage', 'Phone system'],
      industry: 'legal',
      company_size: '20-50',
    },
    assessment: answers({
      q1_work_area: 'admin_ops',
      q2_daily_tasks: ['processing', 'scheduling', 'calls'],
      q3_computer_pct: 70,
      q4_repetitive: '5',
      q8_tools_used: ['none'],
      q9_ai_usage: ['none'],
      q10_ai_output: 'as_is',
      q11_confidence: '1',
      q12_error_detection: 'not_enough',
      q_new_tools: 'wait',
      q25_time_available: 'none',
      q26_reason: 'worried',
      q28_value: 'peace',
    }),
  },

  senior_pm: {
    name: 'QA_SeniorPM',
    email: 'qa-senior-pm@awf-test.local',
    description: 'Senior PM, power user, high confidence',
    roleProfile: {
      job_description: 'Senior Project Manager at a digital agency managing 4-5 concurrent client projects. I coordinate cross-functional teams of designers, developers, and copywriters.',
      pain_point_task: 'Writing weekly status reports for multiple stakeholders — each client wants different formats, different KPIs, and different levels of detail.',
      typical_morning: 'Review Jira boards for all projects, check Slack for overnight blockers, prepare for daily standups, update resource allocation spreadsheet.',
      tools_used: ['Jira', 'Slack', 'Notion', 'Google Workspace', 'ChatGPT', 'Claude', 'GitHub Copilot'],
      industry: 'technology',
      company_size: '50-100',
    },
    assessment: answers({
      q1_work_area: 'project_mgmt',
      q2_daily_tasks: ['managing', 'presentations', 'data'],
      q3_computer_pct: 85,
      q4_repetitive: '2',
      q8_tools_used: ['chatgpt', 'claude', 'copilot'],
      q9_ai_usage: ['write', 'analyze', 'brainstorm', 'summarize'],
      q10_ai_output: 'starting_point',
      q11_confidence: '4',
      q12_error_detection: 'caught_fast',
      q_new_tools: 'jump_in',
      q25_time_available: '3-5',
      q26_reason: 'ahead',
      q28_value: 'hands_on',
    }),
  },

  mid_sales: {
    name: 'QA_MidSales',
    email: 'qa-mid-sales@awf-test.local',
    description: 'Mid-level sales, curious beginner, moderate AI exposure',
    roleProfile: {
      job_description: 'Account Executive at a B2B SaaS company. I manage 40+ accounts, do discovery calls, write proposals, and forecast pipeline.',
      pain_point_task: 'Personalizing outreach emails for prospects — researching each company and writing tailored first-touch emails takes 20+ minutes each.',
      typical_morning: 'Check CRM for follow-ups due today, review new leads from marketing, prep for 3-4 discovery calls, update pipeline forecast.',
      tools_used: ['Salesforce', 'Outreach.io', 'LinkedIn', 'Google Workspace', 'ChatGPT'],
      industry: 'software',
      company_size: '100-200',
    },
    assessment: answers({
      q1_work_area: 'sales',
      q2_daily_tasks: ['clients', 'writing', 'research'],
      q3_computer_pct: 75,
      q4_repetitive: '3',
      q8_tools_used: ['chatgpt'],
      q9_ai_usage: ['write', 'question'],
      q10_ai_output: 'minor_edits',
      q11_confidence: '2',
      q12_error_detection: 'caught_slow',
      q_new_tools: 'show_me',
      q25_time_available: '1-2',
      q26_reason: 'curious',
      q28_value: 'hands_on',
    }),
  },
};

export const ALL_PROFILE_KEYS = Object.keys(PROFILES);
